// Regenerates src/game/guesses.ts from `an-array-of-english-words`.
// Run with `npm run build:guesses` after changing WORD_LENGTH or the answer list.
import { writeFileSync } from 'node:fs'
import words from 'an-array-of-english-words' with { type: 'json' }
import { ANSWERS } from '../src/game/words.ts'
import { WORD_LENGTH } from '../src/game/types.ts'

const fits = new RegExp(`^[a-z]{${WORD_LENGTH}}$`)

const misfits = ANSWERS.filter((w) => !fits.test(w))
if (misfits.length) throw new Error(`answers are not ${WORD_LENGTH} letters: ${misfits.join(', ')}`)

// Union in the answers: a few (fahrenheit, wednesdays) aren't in the dictionary
// and every answer has to be guessable.
const all = [...new Set([...words.filter((w) => fits.test(w)), ...ANSWERS])].sort()

// One flat string rather than a quoted array: ~30KB smaller over the wire.
const flat = all.join('')

writeFileSync(
  new URL('../src/game/guesses.ts', import.meta.url),
  `// GENERATED by scripts/build-guesses.mjs — do not edit by hand.
// ${all.length} words of ${WORD_LENGTH} letters, stored as one flat string and
// sliced apart in isValidGuess. Regenerate with \`npm run build:guesses\`.
export const GUESSES_FLAT =
  '${flat}'
`,
)

console.log(`wrote ${all.length} words of ${WORD_LENGTH} letters (${(flat.length / 1024) | 0} KB raw)`)
