/**
 * Regenerates src/game/guesses.ts from the `an-array-of-english-words` package.
 *
 * That package holds ~275k words of every length; only the WORD_LENGTH ones are
 * any use to us, and bundling the rest would cost megabytes. So we filter here,
 * at build time, and commit the result — the npm package stays a devDependency
 * and never reaches the browser.
 *
 * Run with `npm run build:guesses` after changing WORD_LENGTH or the answer list.
 */
import { writeFileSync } from 'node:fs'
import words from 'an-array-of-english-words' with { type: 'json' }
import { ANSWERS } from '../src/game/words.ts'
import { WORD_LENGTH } from '../src/game/types.ts'

const fits = new RegExp(`^[a-z]{${WORD_LENGTH}}$`)

const misfits = ANSWERS.filter((w) => !fits.test(w))
if (misfits.length) throw new Error(`answers are not ${WORD_LENGTH} letters: ${misfits.join(', ')}`)

// The answer list is unioned in because a handful of answers (proper nouns and
// the like: fahrenheit, wednesdays) aren't in the dictionary, and every answer
// must be guessable.
const all = [...new Set([...words.filter((w) => fits.test(w)), ...ANSWERS])].sort()

// Stored as one flat string, sliced back apart at load. A quoted array of the
// same words costs ~30KB more over the wire and buys nothing.
const flat = all.join('')

writeFileSync(
  new URL('../src/game/guesses.ts', import.meta.url),
  `// GENERATED by scripts/build-guesses.mjs — do not edit by hand.
// ${all.length} words of ${WORD_LENGTH} letters, stored as one flat string and
// sliced apart in isValidGuess. Regenerate with \`npm run build:guesses\`.
export const GUESSES_FLAT =
  '${flat}'
`,
)

console.log(`wrote ${all.length} words of ${WORD_LENGTH} letters (${(flat.length / 1024) | 0} KB raw)`)
