/**
 * Regenerates src/game/guesses.ts from the `an-array-of-english-words` package.
 *
 * That package holds ~275k words of every length; only the WORD_LENGTH ones are
 * any use to us, and bundling the rest would cost megabytes. So we filter here,
 * at build time, and commit the result — the npm package stays a devDependency
 * and never reaches the browser.
 *
 * Run with `npm run build:guesses` after changing WORD_LENGTH or the answer list.
 *
 * types.ts and words.ts are read as text rather than imported: this is plain
 * node, which can't load TypeScript, and adding a TS runner to the toolchain to
 * read two constants isn't worth it.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import words from 'an-array-of-english-words' with { type: 'json' }

const read = (name) => readFileSync(new URL(`../src/game/${name}`, import.meta.url), 'utf8')

const wordLength = Number(read('types.ts').match(/export const WORD_LENGTH = (\d+)/)?.[1])
if (!wordLength) throw new Error('could not find WORD_LENGTH in types.ts')

const answers = [...read('words.ts').matchAll(/'([a-z]+)'/g)].map((m) => m[1])
if (!answers.length) throw new Error('could not find any answers in words.ts')

const fits = new RegExp(`^[a-z]{${wordLength}}$`)
const misfits = answers.filter((w) => !fits.test(w))
if (misfits.length) throw new Error(`answers are not ${wordLength} letters: ${misfits.join(', ')}`)

// The answer list is unioned in because a handful of answers (proper nouns and
// the like: fahrenheit, wednesdays) aren't in the dictionary, and every answer
// must be guessable.
const all = [...new Set([...words.filter((w) => fits.test(w)), ...answers])].sort()

// Stored as one flat string, sliced back apart at load. A quoted array of the
// same words costs ~30KB more over the wire and buys nothing.
const flat = all.join('')

writeFileSync(
  new URL('../src/game/guesses.ts', import.meta.url),
  `// GENERATED by scripts/build-guesses.mjs — do not edit by hand.
// ${all.length} words of ${wordLength} letters, stored as one flat string and
// sliced apart in isValidGuess. Regenerate with \`npm run build:guesses\`.
export const GUESSES_FLAT =
  '${flat}'
`,
)

console.log(`wrote ${all.length} words of ${wordLength} letters (${(flat.length / 1024) | 0} KB raw)`)
